name: isi_analysis
channels:
- conda-forge
- defaults
dependencies:
- python==3.8*
- pip
- line_profiler
- tzlocal
- pytables
- docopt
- dill
- numpy
- imbalanced-learn
- pandas
- pandas-flavor
- h5py
- lmfit
- matplotlib
- psutil
- opencv
- hdbscan
- scipy
- patsy
- nose
- statsmodels
- joblib
- quantities
- scikit-learn
- tabulate
- tqdm
- openpyxl
- dask
- distributed
- fastparquet
- pyarrow
- python-snappy
- datashader
- holoviews
- pynndescent
- outdated
- tabulate
- numdifftools
- sklearn-pandas
- seaborn